### ISSUE TITLE
Enable ES6 proxy on bable bot.

### ISSUE THREAD

**Issue by hemanth** [oftn/oftn-bot#50]
```
--harmony-proxies
```

//cc @ljharb

**Comment by brigand** [comment]
The right repo for this is actually https://github.com/brigand/docker-js-eval

**Comment by hemanth** [comment]
:+1:

**Comment by brigand** [comment]
It's fixed in babelbot anyway, e.g. `nh> typeof Proxy`. You can close this.

**Comment by ljharb** [comment]
Harmony flags should never be used except for experimentation, and the bot is meant to be used to demonstrate productionizable code. When the babel PR merges, it will not include any harmony flags.

**Comment by hemanth** [comment]
:+1:
